# Hospital Patient Data Analysis

Name: Ashar Khan

Batch: Data Science Weekday – Hyderabad  

This assignment focuses on analyzing hospital patient and billing data by applying data cleaning, aggregation, merging, and transformation techniques. The objective is to prepare a clean and structured dataset that can be used for further business analysis such as revenue generation and doctor performance evaluation.

In [2]:
import pandas as pd
import numpy as np

In this step, we import the required libraries for data analysis.

Pandas is used for handling structured data such as tables. It provides powerful tools for filtering, grouping, merging, and cleaning data. NumPy is used for numerical operations and supports efficient calculations on large datasets.

These libraries are standard tools in data analysis and are widely used in real-world projects. They allow us to process and analyze data efficiently.

In [4]:
df = pd.read_csv(r"/content/Patient_Data.csv")

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

The dataset is loaded using the read_csv() function from pandas.

The info() function provides a summary of the dataset, including:
- Number of rows and columns
- Data types of each column
- Presence of missing values

The head() function displays the first few rows of the dataset, helping us understand how the data is structured.

Insight:
At this stage, we identify which columns are useful for analysis and check for missing or inconsistent data. This step is crucial because understanding the dataset before processing helps avoid errors in later stages.

In [5]:
df = df[['PatientID', 'Department', 'Doctor', 'BillAmount']]
df.head()

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

From the complete dataset, only relevant columns are selected:
PatientID, Department, Doctor, and BillAmount.

These columns are directly related to billing and analysis. Other columns such as administrative details are not required for this task.

Insight:
Reducing the dataset to only relevant columns improves performance and clarity. It also ensures that analysis is focused only on meaningful attributes, which is an important practice in data analysis workflows.

# Already handled by selecting relevant columns

Administrative columns like ReceptionistID and CheckInTime are excluded from the dataset.

These columns do not contribute to billing analysis and may introduce unnecessary complexity.

Removing irrelevant data helps in simplifying the dataset and improves efficiency during processing and analysis.

In [6]:
dept_bill = df.groupby('Department')['BillAmount'].sum()
print(dept_bill)

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

The groupby() function is used to group data based on the Department column.

For each department, the total bill amount is calculated using the sum() function.

This operation aggregates the data and provides a summary of revenue generated by each department.

Insight:
This analysis helps identify which departments contribute the most to hospital revenue.
For example, departments like Cardiology or Neurology may show higher billing due to specialized treatments.

This information can be used by hospital management to:
- Allocate resources efficiently
- Identify high-performing departments
- Plan business strategies

In [7]:
df.drop_duplicates(subset='PatientID', inplace=True)

Duplicate records are removed based on PatientID.

In real-world hospital data, a patient may appear multiple times due to follow-ups or repeated visits. However, for this analysis, we want to consider each patient only once.

Insight:
Removing duplicates ensures that data is not counted multiple times, which could lead to incorrect analysis such as inflated billing values or misleading trends.

This step is critical for maintaining data accuracy and reliability.

In [8]:
## Handle Missing Values
mean_bill = df['BillAmount'].mean()
df['BillAmount'] = df['BillAmount'].fillna(mean_bill)

Missing values in the BillAmount column are replaced with the mean of the column.

The mean is calculated using the mean() function, and missing values are filled using fillna().

Insight:
Handling missing values is essential because they can cause errors in calculations and visualizations.

Using the mean ensures that the overall distribution of data remains balanced without removing rows.
This method is commonly used when the missing data is numerical and does not follow a specific pattern.

Proper handling of missing values improves data quality and ensures accurate analysis.

## Merge Billing Dataset

In [9]:
billing = pd.read_csv(r"/content/Billing_Data.csv")

merged_df = pd.merge(df, billing, on='PatientID', how='inner')
merged_df.head()

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Neurology,Dr. John,6233.333333,1500,3500
2,103,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Dermatology,Dr. Rose,6233.333333,1000,4000

The patient dataset is merged with the billing dataset using the PatientID column as a common key.

An inner join is used, which means only matching records from both datasets are included.

Insight:
Merging datasets is a fundamental operation in data analysis. It allows us to combine information from multiple sources into a single dataset.

In this case, merging provides a complete view of each patient, including both personal and billing details.

This combined dataset can be used for advanced analysis such as:
- Revenue analysis
- Doctor performance
- Patient spending patterns

In [10]:
new_patients = pd.DataFrame({
    'PatientID': [201, 202],
    'Department': ['Orthopedics', 'Cardiology'],
    'Doctor': ['Dr. X', 'Dr. Y'],
    'BillAmount': [8000, 9000]
})

df = pd.concat([df, new_patients], axis=0)
df.tail()

   PatientID   Department     Doctor   BillAmount
2        103  Orthopedics    Dr. Lee  7500.000000
3        104   Cardiology  Dr. Smith  6200.000000
4        105  Dermatology   Dr. Rose  6233.333333
0        201  Orthopedics      Dr. X  8000.000000
1        202   Cardiology      Dr. Y  9000.000000

New patient records are added to the dataset using row-wise concatenation.

The concat() function is used with axis=0, which appends rows to the existing dataset.

Insight:
This simulates real-world scenarios where new data is continuously generated and added to existing datasets.

Handling such dynamic data is an important skill in data analysis, especially in industries like healthcare, finance, and e-commerce.

In [11]:
# ADD NEW COLUMNS
extra_columns = pd.DataFrame({
    'InsuranceCovered': ['Yes'] * len(df),
    'FinalAmount': df['BillAmount'] * 0.9
})

df = pd.concat([df, extra_columns], axis=1)
df.head()

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.000000,Yes,4500.0
1,102,Neurology,Dr. John,6233.333333,Yes,5610.0
2,103,Orthopedics,Dr. Lee,7500.000000,Yes,6750.0
3,104,Cardiology,Dr. Smith,6200.000000,Yes,5580.0
4,105,Dermatology,Dr. Rose,6233.333333,Yes,5610.0

New columns are added using column-wise concatenation.

The InsuranceCovered column indicates whether insurance is applied.
The FinalAmount column represents the payable amount after applying a 10% reduction.

Insight:
Adding new columns is a form of feature engineering, which is widely used in data analysis and machine learning.

The FinalAmount helps in understanding actual revenue after insurance deductions, which is more meaningful than raw billing data.

This step enhances the dataset and makes it more useful for decision-making.

In [12]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 1
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         7 non-null      int64
 1   Department        7 non-null      object
 2   Doctor            7 non-null      object
 3   BillAmount        7 non-null      float64
 4   InsuranceCovered  7 non-null      object
 5   FinalAmount       7 non-null      float64
dtypes: float64(2), int64(1), object(3)
memory usage: 392.0+ bytes

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.000000,Yes,4500.0
1,102,Neurology,Dr. John,6233.333333,Yes,5610.0
2,103,Orthopedics,Dr. Lee,7500.000000,Yes,6750.0
3,104,Cardiology,Dr. Smith,6200.000000,Yes,5580.0
4,105,Dermatology,Dr. Rose,6233.333333,Yes,5610.0

The final dataset is checked using info() and head().

This ensures that:
- All transformations are correctly applied
- No missing values remain
- Data structure is consistent

This step is important for validating the final output before further analysis or submission.

## Conclusion

In this assignment, hospital patient and billing data were analyzed using various data processing techniques.

Data cleaning steps such as removing duplicates and handling missing values improved the quality and reliability of the dataset.

Aggregation using groupby provided insights into department-wise revenue, helping identify key contributors to hospital income.

Merging datasets allowed integration of patient and billing information, creating a comprehensive dataset for analysis.

Concatenation techniques were used to simulate real-world scenarios where new data and features are added over time.

Overall, this assignment demonstrates practical skills in data preprocessing, transformation, and analysis, which are essential for real-world data analytics and machine learning applications.